[package]
name = "torrent-title-parser"
version = "0.1.0"
edition = "2021"
description = "A Rust library for parsing torrent titles"

[dependencies]
chrono = "0.4.39"
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
