[package]
name = "torrent-title-parser"
version = "0.1.0"
edition = "2021"
description = "A Rust library for parsing torrent titles"

[dependencies]
chrono = "0.4.39"
fancy-regex = "0.14.0"
lazy_static = "1.5.0"
regex = "1.11.1"
thiserror = "1.0"
