use torrent_title_parser::parse_title;

#[test]
fn test_languages_detection() {
    let test_cases = vec![
        ("Deadpool 2016 1080p BluRay DTS Rus Ukr 3xEng HDCL", vec!["ru", "uk"]),
        ("VAIANA: MOANA (2017) NL-Retail [2D] EAGLE", vec!["nl"]),
        ("De Noodcentrale S02E05 FLEMISH 540p WEBRip AAC H 264", vec!["nl"]),
        ("The Intern 2015 TRUEFRENCH 720p BluRay x264-PiNKPANTERS", vec!["fr"]),
        ("After Earth 2013 VFF BDrip x264 YJ", vec!["fr"]),
        ("127.Heures.FRENCH.DVDRip.AC3.XViD-DVDFR", vec!["fr"]),
        ("Color.Of.Night.Unrated.DC.VostFR.BRrip.x264", vec!["fr"]),
        ("Le Labyrinthe 2014 Multi-VF2 1080p BluRay x264-PopHD", vec!["fr"]),
        ("Maman, j'ai raté l'avion 1990 VFI 1080p BluRay DTS x265-HTG", vec!["fr"]),
        ("South.Park.S21E10.iTALiAN.FiNAL.AHDTV.x264-NTROPiC", vec!["it"]),
        ("2- English- {SDH}.srt", vec!["en"]),
        ("1_ English-Subs.srt", vec!["en"]),
        ("House S 1 CD 1-6 svensk, danska, norsk, finsk sub", vec!["da", "fi", "sv", "no"]),
        ("Svein.Og.Rotta.NORSK.Nordic.Subs.2006", vec!["da", "fi", "sv", "no"]),
        ("Borat med Norsk Undertekst", vec!["no"]),
        ("Subs/21_Bokmal.srt", vec!["no"]),
        ("Subs/nob.srt", vec!["no"]),
        ("Subs/5_nor.srt", vec!["no"]),
        ("Curious.George.2.Follow.That.Monkey.2009.DK.SWE.UK.PAL.DVDR-CATC", vec!["da", "sv"]),
        ("Yes.Man.Dk-Subs.2009.dingel", vec!["da"]),
        ("Dan-SDH.srt", vec!["da"]),
        ("dan.srt", vec!["da"]),
        ("Red Riding 1974 [2009 PAL DVD][En Subs[Sv.No.Fi]", vec!["en", "fi", "sv"]),
        ("Comme une Image (Look at Me) [2004 PAL DVD][Fr Subs[Sv.Da.No]", vec!["fr", "sv"]),
        ("A.Good.Day.To.Die.Hard.2013.SWESUB.DANSUB.FiNSUB.720p.WEB-DL.-Ro", vec!["da", "fi", "sv"]),
        ("The.Prisoner.1967-1968.Complete.Series.Subs.English+Nordic", vec!["en", "da", "fi", "sv", "no"]),
        ("Royal.Pains.S05E02.HDTV.subtitulado.esp.sc.avi", vec!["es"]),
        ("Desmembrados (2006) [HDrip-XviD-AC3][Castellano]", vec!["es"]),
        ("10_Spanish-Subs.srt", vec!["es"]),
        ("Patriot Games [1992] Eng, Ger, Cze, Hun, Pol + multisub  DVDrip", vec!["en", "de", "pl", "cs", "hu"]),
        ("Elvis Presley - La via del Male (King creole) - IT EN FR DE ES", vec!["en", "fr", "es", "it", "de"]),
        ("FernGully [H264 - Ita Dut Fre Ger Eng Spa Aac - MultiSub]", vec!["en", "fr", "es", "it", "de", "nl"]),
        ("Jesus de Montreal / Jesus of Montreal - subtitulos espanol", vec!["es"]),
        ("Los.Vengadores.DVDR español ingles clon", vec!["en", "es"]),
        ("EMPIRE STATE 2013 DVDRip TRNC English and Española Latin", vec!["en", "la", "es"]),
        ("Mary Poppins Returns 2019 DVDRip LATINO-1XBET", vec!["la"]),
        ("Los Simpsons S18 E01 Latino", vec!["la"]),
        ("Spider-Man (2002) Blu-Ray [720p] Dual Ingles-Español", vec!["en", "es"]),
        ("Abuela (2015) 1080p BluRay x264 AC3 Dual Latino-Inglés", vec!["en", "la"]),
        ("Dumbo.2019.1080p.Dual.Lat", vec!["la"]),
        ("A.Score.to.Settle.2019.lati.mp4", vec!["la"]),
        ("[S0.E04] Gambit królowej - Gra środkowa.Spanish Latin America.srt", vec!["la"]),
        ("Latin American.spa.srt", vec!["la"]),
        ("Men in Black International 2019 (inglês português)", vec!["en", "pt"]),
        ("Assassins (1995) Sylvester Stallone.DVDrip.XviD - Italian Englis", vec!["en", "it"]),
        ("El Club de la Lucha[dvdrip][spanish]", vec!["es"]),
        ("The Curse Of The Weeping Woman 2019 BluRay 1080p Tel+Tam+hin+eng", vec!["en", "hi", "te", "ta"]),
        ("Inception 2010 1080p BRRIP[dual-audio][eng-hindi]", vec!["en", "hi"]),
        ("Inception (2010) 720p BDRip Tamil+Telugu+Hindi+Eng", vec!["en", "hi", "te", "ta"]),
        ("Subs/Dear.S01E02.WEBRip.x265-ION265/34_tam.srt", vec!["ta"]),
        ("Subs/Dear.S01E02.WEBRip.x265-ION265/35_tel.srt", vec!["te"]),
        ("Dabangg 3 2019 AMZN WebRip Hindi 720p x264", vec!["hi"]),
        ("Quarantine [2008] [DVDRiP.XviD-M14CH0] [Lektor PL] [Arx]", vec!["pl"]),
        ("The Mandalorian S01E06 POLISH WEBRip x264-FLAME", vec!["pl"]),
        ("Carros 2 Dublado - Portugues BR (2011)", vec!["pt"]),
        ("A.Simple.Plan.1998.720p.BDRIP.X264.dublado.portugues.BR.gmenezes", vec!["pt"]),
        ("American.Horror.Story.S01E01.720p. PORTUGUÊS BR", vec!["pt"]),
        ("Angel.S05E19.legendado.br.rmvb", vec!["pt"]),
        ("Grimm S01E11 Dublado BR [ kickUploader ]", vec!["pt"]),
        ("InuYasha.EP161.ptBR.subtitles.[inuplace.com.br].avi", vec!["pt"]),
        ("Ghost.Rider.DivX_Gamonet(Ingles-Port.BR)-AC3.avi", vec!["en", "pt"]),
        ("I Am David  legendado pt/br", vec!["pt"]),
        ("Lone Wolf and Cub 6 movies - legendas BR", vec!["pt"]),
        ("Wonder Woman Season 3 (H.264 1080p; English/Portuguese-BR)", vec!["en", "pt"]),
        ("MIB 3 - Homens de Preto 2012 ( Audio EN-BR - Leg BR  Mkv 1280x69", vec!["en", "pt"]),
        ("my wife is a gangster 3 legendado em PT(BR)", vec!["pt"]),
        ("A.Clockwork.Orange.1971.BRDRIP.1080p.DUAL.PORT-BR.ENG.gmenezes.m", vec!["en", "pt"]),
        ("Superman I - O Filme 1978 Leg. BR - Mkv 1280x528", vec!["pt"]),
        ("Subs/Brazilian.por.srt", vec!["pt"]),
        ("Brazilian Portuguese.por.srt", vec!["pt"]),
        ("[S0.E07] Gambit królowej - Gra końcowa.Portuguese Brazil.srt", vec!["pt"]),
        ("The Hit List (2011) DVD NTSC WS (eng-fre-pt-spa) [Sk]", vec!["en", "fr", "es"]),
        ("[POPAS] Neon Genesis Evangelion: The End of Evangelion [jp_PT-pt", vec!["ja", "pt"]),
        ("Zola Maseko - Drum (2004) PT subs", vec!["pt"]),
        ("Idrissa Ouedraogo - Yaaba (1989) EN ES FR PT", vec!["en", "fr", "es"]),
        ("Metallica.Through.The.Never.2013 O Filme(leg.pt-pt)", vec!["pt"]),
        ("Dinossauro (2000) --[ Ing / Pt / Esp ]", vec!["en", "es"]),
        ("The Guard 2011.DK.EN.ES.HR.NL.PT.RO.Subtitles", vec!["en", "es", "ro", "hr", "nl", "da"]),
        ("Titan.A.E.2000 720p  HDTV DTS Eng Fra Hun Rom Rus multisub", vec!["en", "fr", "ru", "hu", "ro"]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Latin American es.ass", vec!["la"]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Brazilian pt.ass", vec!["pt"]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.pt.ass", vec!["pt"]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.es.ass", vec!["es"]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.de.ass", vec!["de"]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.it.ass", vec!["it"]),
        ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.ar.ass", vec!["ar"]),
        ("Subs(ara,fre,ger).srt", vec!["fr", "de", "ar"]),
        ("Subs(chi,eng,ind,kor,may,tha,vie).srt", vec!["en", "ko", "zh", "vi", "id", "th", "ms"]),
        ("Miami.Bici.2020.1080p.NETFLIX.WEB-DL.DDP5.1.H.264.EN-ROSub-ExtremlymTorrents", vec!["en", "ro"]),
        ("26_Romanian.srt", vec!["ro"]),
        ("4_Bulgarian.srt", vec!["bg"]),
        ("18_srp.srt", vec!["sr"]),
        ("Aranyelet.S01.HUNGARIAN.1080p.WEBRip.DDP5.1.x264-SbR[rartv]", vec!["hu"]),
        ("Ponyo[2008]DvDrip-H264 Quad Audio[Eng Jap Fre Spa]AC3 5.1[DXO]", vec!["en", "ja", "fr", "es"]),
        ("The Mechanic [1972] Eng,Deu,Fra,Esp,Rus + multisub DVDrip", vec!["en", "fr", "es", "de", "ru"]),
        ("Mommie Dearest [1981 PAL DVD][En.De.Fr.It.Es Multisubs[18]", vec!["en", "fr", "es", "de"]),
        ("Pasienio sargyba S01E03 (2016 WEBRip LT)", vec!["lt"]),
        ("24_Lithuanian.srt", vec!["lt"]),
        ("25_Latvian.srt", vec!["lv"]),
        ("13_Estonian.srt", vec!["et"]),
        ("Ip.Man.4.The.Finale.2019.CHINESE.1080p.BluRay.x264.TrueHD.7.1.Atmos-HDC", vec!["zh"]),
        ("should parse CHT language", vec!["zh"]),
        ("Inuyasha_TV+Finale+OVA+Film+CD+Manga+Other; dub jpn,chn,eng sub chs (2019-09-21)", vec!["en", "ja", "zh"]),
        ("Initial D Live Action 2005 ENG/CHI", vec!["en", "zh"]),
        ("Wolf.Warrior.2015.720p.BluRay.x264.Mandarin.AAC-ETRG", vec!["zh"]),
        ("Traditional Chinese.chi.srt", vec!["zh"]),
        ("Subs/Promare - Chinese (Traditional).ass", vec!["zh"]),
        ("Berserk 01-25 [dual audio JP,EN] MKV", vec!["en", "ja"]),
        ("FLCL S05.1080p HMAX WEB-DL DD2.0 H 264-VARYG (FLCL: Shoegaze Dual-Audio Multi-Subs)", vec![]),
        ("Shinjuku Swan 2015 JAP 1080p BluRay x264 DTS-JYK", vec!["ja"]),
        ("Wet.Woman.in.the.Wind.2016.JAPANESE.1080p.BluRay.x264-iKiW", vec!["ja"]),
        ("All.Love.E146.KOR.HDTV.XViD-DeBTV", vec!["ko"]),
        ("The.Nun.2018.KORSUB.HDRip.XviD.MP3-STUTTERSHIT", vec!["ko"]),
        ("Burning.2018.KOREAN.720p.BluRay.H264.AAC-VXT", vec!["ko"]),
        ("Atonement.2017.KOREAN.ENSUBBED.1080p.WEBRip.x264-VXTT", vec!["en", "ko"]),
        ("A Freira (2018) Dublado HD-TS 720p", vec!["pt"]),
        ("Escobar El Patron Del Mal Capitulo 91 SD (2012-10-10) [SiRaDuDe]", vec!["pt"]),
        ("Bleach - 215 ao 220 - [DB-BR]", vec!["pt"]),
        ("Joker.2019.MULTi.Bluray.1080p.Atmos.7.1.En.Fr.Sp.Pt-DDR[EtHD]", vec!["en", "fr"]),
        ("Dilbert complete series + en subs", vec!["en"]),
        ("The Next Karate Kid (1994) NTSC WS -Eng/Fre/Spa/Por- [ctang]", vec!["en", "fr", "es", "pt"]),
        ("arsenico por compasion 1944 Capra spanish castellano", vec!["es", "pt"]),
        ("Un.Homme.Et.Une.Femme.1966.DVDRip.XviD.AR [PT ENG ESP]", vec!["en", "es", "pt"]),
        ("Geminis.2005.Argentina.ESP.ENG.PT.SUBS", vec!["en", "es", "pt"]),
        ("1917 2019 1080p Bluray x264-Sexmeup [Greek Subs] [Braveheart]", vec!["el"]),
        ("The Lion King 1,2,3 Greek Language", vec!["el"]),
        ("The Adams Family (1991) (Greek Subs integratet)", vec!["el"]),
        ("6_Greek.srt", vec!["el"]),
        ("The Insult (2017) [BluRay] [720p] Arabic", vec!["ar"]),
        ("The.Mexican.2001 - Arabic Subs Hardcoded", vec!["ar"]),
        ("Much Loved (2015) - DVDRip x265 HEVC - ARAB-ITA-FRE AUDIO (ENG S", vec!["en", "fr", "it", "ar"]),
        ("42.2013.720p.BluRay.x264.HD4Ar Arab subtitle", vec!["ar"]),
        ("Fauda.S01.HEBREW.1080p.NF.WEBRip.DD5.1.x264-TrollHD[rartv]", vec!["he"]),
        ("madagascar 720p hebrew dubbed.mkv", vec!["Hebrew"]),
        ("Into.the.Night.S01E04.Ayaz.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track17_[heb].srt", vec!["Hebrew"]),
        ("The.Protector.2018.S03.TURKISH.WEBRip.x264-ION10", vec!["Turkish"]),
        ("Recep Ivedik 6 (2020) NETFLIX 720p WEBDL (Turkish) - ExtremlymTorrents", vec!["Turkish"]),
        ("The Insider*1999*[DVD5][PAL][ENG, POL, sub. ROM, TUR]", vec!["English", "Polish", "Romanian", "Turkish"]),
        ("Japanese.Story.2003.1080p.WEBRip.x264-RARBG", vec![]),
        ("[ Torrent9.cz ] The.InBetween.S01E10.FiNAL.HDTV.XviD-EXTREME.avi", vec![]),
        ("Thai Massage (2022) 720p PDVDRip x264 AAC.mkv", vec![]),
        ("Carson Daly 2017 09 13 Dan Harmon 720p HDTV x264-CROOKS", vec![]),
        ("Dan Browns The Lost Symbol S01E03 1080p WEB H264-GLHF", vec![]),
        ("Ben.Ara.2015.1080p.WEBRip.x265-RARBG.mp4", vec![]),
        ("Ara.(A.Break).2008.DVDRip", vec![]),
        ("www.1TamilMV.cz - Mirzapur (2020) S02 EP (01-10) - HQ HDRip - [Tam+ Tel] - x264 - AAC - 1GB - ESub", vec!["en", "te", "ta"]),
        ("www.1TamilMV.cz - The Game of Chathurangam (2023) WEB-DL - 1080p - AVC - (AAC 2.0) [Tamil + Malayalam] - 1.2GB.mkv", vec!["ta", "ml"]),
        ("www.1TamilMV.yt - Anchakkallakokkan (2024) Malayalam HQ HDRip - 720p - HEVC - (DD+5.1 - 192Kbps & AAC) - 750MB - ESub.mkv", vec!["en", "ml"]),
        ("Anatomia De Grey - Temporada 19 [HDTV][Cap.1905][Castellano][www.AtomoHD.nu].avi", vec!["es"]),
        ("Godzilla.x.Kong.The.New.Empire.2024.2160p.BluRay.REMUX.DV.P7.HDR.ENG.LATINO.GER.ITA.FRE.HINDI.CHINESE.TrueHD.Atmos.7.1.H265-BEN.THE.MEN", vec!["en", "zh", "fr", "la", "it", "de", "hi"]),
        ("Sampurna.2023.Bengali.S02.1080p.AMZN.WEB-DL.DD+2.0.H.265-TheBiscuitMan", vec!["bn"]),
        ("Kingdom.of.the.Planet.of.the.Apes.2024.HDRIP.1080P.[xDark [SaveHD] Latin + English + Hindi.mp4", vec!["en", "la", "hi"]),
        ("The Karate Kid Part III 1989 1080p DUAL TİVİBU WEB-DL x264 AAC - HdT", vec!["tr"]),
    ];

    for (input, expected_languages) in test_cases {
        let result = parse_title(input).unwrap();
        assert_eq!(
            result.languages, expected_languages,
            "Incorrect languages detected for {}: Got {:?}, expected {:?}",
            input, result.languages, expected_languages
        );
    }
}

#[test]
fn test_translate_languages() {
    let test_cases = vec![
        ("madagascar 720p hebrew dubbed.mkv", vec!["Hebrew"]),
        (
            "Into.the.Night.S01E04.Ayaz.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track17_[heb].srt",
            vec!["Hebrew"],
        ),
        ("The.Protector.2018.S03.TURKISH.WEBRip.x264-ION10", vec!["Turkish"]),
        (
            "Recep Ivedik 6 (2020) NETFLIX 720p WEBDL (Turkish) - ExtremlymTorrents",
            vec!["Turkish"],
        ),
        (
            "The Insider*1999*[DVD5][PAL][ENG, POL, sub. ROM, TUR]",
            vec!["English", "Polish", "Romanian", "Turkish"],
        ),
        ("Japanese.Story.2003.1080p.WEBRip.x264-RARBG", vec![]),
        ("[ Torrent9.cz ] The.InBetween.S01E10.FiNAL.HDTV.XviD-EXTREME.avi", vec![]),
        ("Thai Massage (2022) 720p PDVDRip x264 AAC.mkv", vec![]),
    ];

    for (input, expected_languages) in test_cases {
        let result = parse_title(input).unwrap();
        assert_eq!(
            result.languages, expected_languages,
            "Incorrect translated languages detected for {}: Got {:?}, expected {:?}",
            input, result.languages, expected_languages
        );
    }
}
