#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    English,
    Italian,
    French,
    Spanish,
    LatinAmericanSpanish,
    German,
    Portuguese,
    Japanese,
    Korean,
    Chinese,
    Russian,
    Ukrainian,
    Greek,
    Lithuanian,
    Latvian,
    Estonian,
    Polish,
    Czech,
    Slovak,
    Hungarian,
    Romanian,
    Bulgarian,
    Croatian,
    Serbian,
    Slovenian,
    Dutch,
    Danish,
    Finnish,
    Norwegian,
    Swedish,
    Turkish,
    Arabic,
    Indonesian,
    Vietnamese,
    Thai,
    Malay,
    Hebrew,
    Persian,

    // Indian Languages
    Hindi,
    Telugu,
    Tamil,
    Malayalam,
    Kannada,
    Marathi,
    Gujarati,
    Bengali,
    Punjabi,
}

impl Language {
    pub fn to_iso_639_1(&self) -> &str {
        match self {
            Language::English => "en",
            Language::Italian => "it",
            Language::French => "fr",
            Language::Spanish => "es",
            Language::LatinAmericanSpanish => "es",
            Language::German => "de",
            Language::Portuguese => "pt",
            Language::Japanese => "ja",
            Language::Korean => "ko",
            Language::Chinese => "zh",
            Language::Russian => "ru",
            Language::Ukrainian => "uk",
            Language::Greek => "el",
            Language::Lithuanian => "lt",
            Language::Latvian => "lv",
            Language::Estonian => "et",
            Language::Polish => "pl",
            Language::Czech => "cs",
            Language::Slovak => "sk",
            Language::Hungarian => "hu",
            Language::Romanian => "ro",
            Language::Bulgarian => "bg",
            Language::Croatian => "hr",
            Language::Serbian => "sr",
            Language::Slovenian => "sl",
            Language::Dutch => "nl",
            Language::Danish => "da",
            Language::Finnish => "fi",
            Language::Norwegian => "no",
            Language::Swedish => "sv",
            Language::Turkish => "tr",
            Language::Arabic => "ar",
            Language::Indonesian => "id",
            Language::Vietnamese => "vi",
            Language::Thai => "th",
            Language::Malay => "ms",
            Language::Hebrew => "he",
            Language::Persian => "fa",
            Language::Hindi => "hi",
            Language::Telugu => "te",
            Language::Tamil => "ta",
            Language::Malayalam => "ml",
            Language::Kannada => "kn",
            Language::Marathi => "mr",
            Language::Gujarati => "gu",
            Language::Bengali => "bn",
            Language::Punjabi => "pa",
        }
    }
}
