#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Quality {
    TeleSync,
    TeleCine,
    SCR,
    BluRay,
    BluRayRemux,
    Remux,
    UHDRip,
    HDRip,
    BRRip,
    BDRip,
    DVDRip,
    VHSRip,
    DVD,
    VHS,
    PPVRip,
    HDTVRip,
    HDTV,
    SATRip,
    TVRip,
    R5,
    WebMux,
    WebRip,
    WebDL,
    WebDLRip,
    Web,
    Cam,
    PDTV,
}

impl Quality {
    pub fn as_str(&self) -> &'static str {
        match self {
            Quality::TeleSync => "TeleSync",
            Quality::TeleCine => "TeleCine",
            Quality::SCR => "SCR",
            Quality::BluRay => "BluRay",
            Quality::BluRayRemux => "BluRay REMUX",
            Quality::Remux => "REMUX",
            Quality::UHDRip => "UHDRip",
            Quality::HDRip => "HDRip",
            Quality::BRRip => "BRRip",
            Quality::BDRip => "BDRip",
            Quality::DVDRip => "DVDRip",
            Quality::VHSRip => "VHSRip",
            Quality::DVD => "DVD",
            Quality::VHS => "VHS",
            Quality::PPVRip => "PPVRip",
            Quality::HDTVRip => "HDTVRip",
            Quality::HDTV => "HDTV",
            Quality::SATRip => "SATRip",
            Quality::TVRip => "TVRip",
            Quality::R5 => "R5",
            Quality::WebMux => "WEBMux",
            Quality::WebRip => "WEBRip",
            Quality::WebDL => "WEB-DL",
            Quality::WebDLRip => "WEB-DLRip",
            Quality::Web => "WEB",
            Quality::Cam => "CAM",
            Quality::PDTV => "PDTV",
        }
    }
}
